application:
  name: kafka-client-k3s
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: java-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
